const data = [
    {
        name: '와퍼 세트',
        price: 10500,
        imgUrl: './imgs/set1.png',
        description: '와퍼 리얼 와퍼 + 프렌치프라이R + 콜라R, 불에 직접 구운 순 쇠고기 패티에 싱싱한 야채가 한가득 버거킹의 대표 메뉴',
        type: 'set',
    },
    {
        name: '불고기와퍼세트',
        price: 10500,
        imgUrl: './imgs/set2.png',
        description: '불고기와퍼 + 프렌치프라이R + 콜라R, 불에 직접 구운 순 쉬고기 패티가 들어간 와퍼에 달콤한 불고기 소스까지',
        type: 'set',
    },
    {
        name: '몬스터와퍼 세트',
        price: 12200,
        imgUrl: './imgs/set3.png',
        description: '디아블로 소스의 매콤함, 불에 직접 구운 100% 순쇠고기 패티와 치킨패티까지 압도적 크기의 몬스터와퍼',
        type: 'set',
    },
    {
        name: '통새우와퍼세트',
        price: 11300,
        imgUrl: './imgs/set4.png',
        description: '입안에서 톡톡 터지는 통새우가 매콤한 스파이시 토마토소스와 100% 순쇠고기 패티를 만나 완성한 통새우와퍼',
        type: 'set',
    },
    {
        name: '콰트로치즈와퍼 세트',
        price: 11300,
        imgUrl: './imgs/set5.png',
        description: '콰트로치즈와퍼 + 프렌치프라이R + 콜라R, 네가지 고품격 치즈와 100% 순쇠고기 패티로 탄생한 버거킹의 스테디셀러, 콰트로치즈와퍼',
        type: 'set',
    },
    {
        name: '리얼 어니언링',
        price: 3500,
        imgUrl: './imgs/side1.png',
        description: '통째로 썰어 더 두툼하고 더 바삭해진',
        type: 'side',
    },
    {
        name: '너겟킹',
        price: 6400,
        imgUrl: './imgs/side2.png',
        description: '바삭하고 촉촉한 부드러운 너겟킹',
        type: 'side',
    },
    {
        name: '21치즈스틱',
        price: 3400,
        imgUrl: './imgs/side3.png',
        description: '21cm의 역대급 사이즈 진하고 고소한 자연 모짜렐라가 가득한 21치즈스틱',
        type: 'side',
    },
    {
        name: '애플파이',
        price: 3200,
        imgUrl: './imgs/pie1.png',
        description: '바삭하고 통사과가 들어있는 따끈한 애플파이',
        type: 'pie',
    },
    {
        name: 'Sundae파이',
        price: 3400,
        imgUrl: './imgs/pie2.png',
        description: '바삭한 초코 크러스트와 허쉬스 아이스크림이 들어간 Sundae파이',
        type: 'pie',
    },
    {
        name: '코카콜라',
        price: 3100,
        imgUrl: './imgs/drink1.png',
        description: '코카콜라로 더 짜릿하게',
        type: 'drink',
    },
    {
        name: '코카콜라 제로',
        price: 3100,
        imgUrl: './imgs/drink2.png',
        description: '100% 짜릿함, 칼로리는 제로',
        type: 'drink',
    },
    {
        name: '스프라이트',
        price: 3100,
        imgUrl: './imgs/drink3.png',
        description: '나를 깨우는 상쾌함',
        type: 'drink',
    },
    {
        name: '스프라이트 제로',
        price: 3100,
        imgUrl: './imgs/drink4.png',
        description: '제대로 상쾌한 맛남 스프라이트 제로',
        type: 'drink',
    },
    {
        name: '미닛메이드',
        price: 3700,
        imgUrl: './imgs/drink5.png',
        description: '자연의 풍부한 영양과 맛',
        type: 'drink',
    },
];

export default data;